steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx-image:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'nginx-deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-southwest1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-pokemon'
