 steps:
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['install', 'stable/keel', '--name', 'keel', '--namespace', 'keel']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-southwest1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-pokemon'