# Etapas de compilación
steps:
  # Actualiza los submódulos de Git en su proyecto
  - name: gcr.io/cloud-builders/git
    args: ['submodule', 'update', '--init']
  # Compila la imagen Docker y la etiqueta con el valor $COMMIT_SHA
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/fc-labs-pro-lab2/pokemon-nginx:app', '-f', 'Dockerfile', '.']
  # Sube la imagen recién creada a Google Container Registry
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/fc-labs-pro-lab2/pokemon-nginx:app']
  # Actualiza el helm release en su clúster de Kubernetes
  - name: alpine/helm
    args: ['upgrade', 'pokemon', 'nginx-chart', '--namespace', 'default', '--set', 'image.tag=app']
    # Especifica la zona y el nombre del clúster de GKE
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-southwest1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-pokemon'

# Imagen a ser creada por la etapa de compilación
images:
  # Etiqueta la imagen final con el valor $COMMIT_SHA
  - gcr.io/fc-labs-pro-lab2/pokemon-nginx:app







