steps:
  # Configura la conexión de Kubernetes en Cloud Build
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=<(gcloud iam service-accounts keys list --iam-account=789404228835@cloudbuild.gserviceaccount.com --format='value(name)') -y
        gcloud auth application-default login
  # Clona el repositorio de GitHub que contiene el código del chart de Helm
  - name: 'gcr.io/cloud-builders/git'
    id: 'Deploy'    id: 'Deploy'
    args: ['clone', '--single-branch', '--branch', 'main', 'https://github.com/Banhendrick/cloud-pokemon.git', 'helm']
    waitFor: [ '-' ]
  # Actualiza el despliegue de Nginx utilizando el chart de Helm
  - name: 'alpine/helm'
    args: ['upgrade', '--install', 'pokemon', 'nginx-chart', '--namespace', 'default', '-f', 'values.yaml']
    env:
      - 'HELM_HOME=/builder/home/.helm'
  #Implementa la actualizacion en el cluster de GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'deployments', 'create', 'cloudbuild-pokemon', '--config', 'cloudconfig.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-southwest1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-pokemon'




