steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pokemon-nginx:app', '-t', 'gcr.io/$PROJECT_ID/pokemon-nginx:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/pokemon-nginx:$BUILD_ID', '.']
  id: 'build-image-pokemon-nginx'
  waitFor: ['-']  # The '-' indicates that this step begins immediately.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/pokemon-nginx:$COMMIT_SHA']
  id: 'push-image-to-container-registry'
  waitFor: ['build-image-pokemon-nginx']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'pokemon-nginx-service'
  - '--image'
  - 'gcr.io/$PROJECT_ID/pokemon-nginx:$COMMIT_SHA'
  - '--region'
  - 'europe-southwest1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  waitFor: ['push-image-to-container-registry']
  id: 'deploy-to-cloud-run'
options:
  logging: GCS_ONLY
images:
- 'gcr.io/$PROJECT_ID/pokemon-nginx:app'
- 'gcr.io/$PROJECT_ID/pokemon-nginx:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/pokemon-nginx:$BUILD_ID'
