steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/helm:${_HELM_VERSION}', '--tag=gcr.io/$PROJECT_ID/helm:latest', '--build-arg', 'HELM_VERSION=v${_HELM_VERSION}', '.' ]
  #args: ['build', '-t', 'gcr.io/$PROJECT_ID/pokemon-nginx:app', '-t', 'gcr.io/$PROJECT_ID/pokemon-nginx:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/pokemon-nginx:$BUILD_ID', '.']
  id: 'build-image-helm'
  waitFor: ['-']  # The '-' indicates that this step begins immediately.

# Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/helm']
  id: 'push-image-to-container-registry'
  waitFor: ['build-image-helm']

# Deploy the Helm chart to GKE
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['upgrade', '--install', 'helm', 'nginx-chart', '-f', 'nginx-chart/templates/values.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  id: 'deploy-nginx-chart'
  waitFor: ['push-image-to-container-registry']

options:
  logging: GCS_ONLY

substitutions:
  _HELM_VERSION: 3.7.0
  _CLOUDSDK_COMPUTE_ZONE: europe-southwest1-a
  _CLOUDSDK_CONTAINER_CLUSTER: gke-pokemon

images:
- 'gcr.io/$PROJECT_ID/helm:${_HELM_VERSION}'
- 'gcr.io/$PROJECT_ID/helm:latest'
#- 'gcr.io/$PROJECT_ID/pokemon-nginx:app'
#- 'gcr.io/$PROJECT_ID/pokemon-nginx:$COMMIT_SHA'
#- 'gcr.io/$PROJECT_ID/pokemon-nginx:$BUILD_ID'
#asd
