steps:
# build the docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pokemon-nginx:app', '-t', 'gcr.io/$PROJECT_ID/pokemon-nginx:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/pokemon-nginx:$BUILD_ID', '.']
  id: 'build-image-pokemon-nginx'
  waitFor: ['-']  # The '-' indicates that this step begins immediately.

#Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/pokemon-nginx:$COMMIT_SHA']
  id: 'push-image-to-container-registry'
  waitFor: ['build-image-pokemon-nginx']

# Deploy the Helm chart to GKE
- name: 'gcr.io/$PROJECT_ID/cloud-builders-helm'
  args: ['upgrade', '--install', 'filebeat', '--namespace', 'filebeat', 'stable/filebeat']
  
options:
  logging: GCS_ONLY
images:
- 'gcr.io/$PROJECT_ID/pokemon-nginx:app'
- 'gcr.io/$PROJECT_ID/pokemon-nginx:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/pokemon-nginx:$BUILD_ID'
