# Etapas de compilación
steps:
  # Compila la imagen Docker y la etiqueta con el valor $COMMIT_SHA
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/fc-labs-pro-lab2/pokemon-nginx:$COMMIT_SHA', '-f', 'Dockerfile', '.']
  # Sube la imagen de Nginx recién creada a Google Container Registry
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/fc-labs-pro-lab2/pokemon-nginx:$COMMIT_SHA']
  - name: gcr.io/fc-labs-pro-lab2/helm:latest
    #entrypoint: /bin/sh
    args: ['upgrade', '--install', 'pokemon', 'nginx-chart', '--namespace', 'default', '--set', 'image.tag=$COMMIT_SHA']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-southwest1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-pokemon'
# Imágenes a ser creadas por la etapa de compilación
