version: '3'

services:

    # nginx
    nginx:
        image: nginx:1.23-alpine-slim
        container_name: nginx-container
        ports:
            - "8080:80"
        restart: always

    # php
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-container
        ports:
            - "9000:9000"
        restart: always

    # mysql
    mysql:
        image: mysql:8.0.32
        container_name: mysql-container
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root


    # memcached
    memcached:
        image: memcached:1.6.19
        container_name: memcached-container
        ports:
            - "11211:11211"
        restart: always

    #redis
    redis:
        image: redis:7.0.10
        container_name: redis-container
        ports:
            - "6379:6379"


  
