version: '3'
#como colocar bien los volumes?

services:

    # nginx
    nginx:
        image: nginx:1.23-alpine-slim
        container_name: nginx-container
        ports:
            - "8080:80"
        restart: always
        volumes:
            - ./:/var/www/
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php81-service
            - mysql8-service
            - memcached-service
            - redis-service

    # php
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-container
        ports:
            - "9000:9000"
        restart: always
        volumes:
            - ./:/var/www/
        networks:
            - local-network

    # mysql
    mysql:
        image: mysql:8.0.32
        container_name: mysql-container
        ports:
            - "3306:3306"
        volumes:
            - ./mydb:/var/lib/mysql
            - ./opt/db:/docker-entrypoint-initdb.d
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            
        networks:
            - local-network

    # memcached
    memcached:
        image: memcached:1.6.19
        container_name: memcached-container
        ports:
            - "11211:11211"
        restart: always
        networks:
            - local-network

    #redis
    redis:
        image: redis:7.0.10
        container_name: redis-container
        ports:
            - "6379:6379"
        networks:
            - local-network

  
