apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
      # tiene que coincidir con el service
        io.kompose.service: nginx
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: nginx-container
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}