version: '3'

services:

    # nginx
    nginx:
        image: banhendrick/nginx-php-pokemon:latest
        container_name: nginx-container
        ports:
            - "8080:80"
        restart: always

    # mysql
    mysql:
        image: banhendrick/mysql-pokemon:v1
        container_name: mysql-container
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root


    # memcached
    memcached:
        image: memcached:1.6.19
        container_name: memcached-container
        ports:
            - "11211:11211"
        restart: always

    #redis
    redis:
        image: redis:7.0.10
        container_name: redis-container
        ports:
            - "6379:6379"


  
