apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: memcached
  name: memcached
spec:
  type: LoadBalancer
  ports:
  - name: "11211"
    port: 11211
    targetPort: 11211
  selector:
    io.kompose.service: memcached

