apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql8
  name: mysql8
spec:
  selector:
    matchLabels:
      io.kompose.service: mysql8
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql8
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: mysql:8.0.32
        name: mysql-container
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql8-claim0
        - mountPath: /docker-entrypoint-initdb.d
          name: mysql8-claim1
      restartPolicy: Always
      volumes:
      - name: mysql8-claim0
        persistentVolumeClaim:
          claimName: mysql8-claim0
      - name: mysql8-claim1
        persistentVolumeClaim:
          claimName: mysql8-claim1
status: {}
