apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  selector:
    matchLabels:
      io.kompose.service: mysql
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: banhendrick/mysql-pokemon:v1
        imagePullPolicy: IfNotPresent
        name: mysql-container
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
