apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
  # tiene que coincidir con el deployment
    io.kompose.service: nginx
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  
  
